import pygame 

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600

NUMBER_OF_CELL_WIDTH = 50
NUMBER_OF_CELL_HEIGHT=30
GAME_OVER_EVENT = pygame.USEREVENT + 1
APPLE_EATEN_EVENT = pygame.USEREVENT + 2

CELL_WIDTH = SCREEN_WIDTH // NUMBER_OF_CELL_WIDTH
CELL_HEIGHT = SCREEN_HEIGHT // NUMBER_OF_CELL_HEIGHT


WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)